// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const SUPABASE_STORAGE_KEY = "bjjmanager-auth-session";

const createSessionStorageAdapter = () => {
  const memoryStorage = new Map<string, string>();

  const getStorage = () => {
    if (typeof window !== "undefined" && window.sessionStorage) {
      return window.sessionStorage;
    }

    return {
      getItem: (key: string) => memoryStorage.get(key) ?? null,
      setItem: (key: string, value: string) => {
        memoryStorage.set(key, value);
      },
      removeItem: (key: string) => {
        memoryStorage.delete(key);
      },
    };
  };

  return {
    getItem: (key: string) => getStorage().getItem(key),
    setItem: (key: string, value: string) => getStorage().setItem(key, value),
    removeItem: (key: string) => getStorage().removeItem(key),
  };
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storageKey: SUPABASE_STORAGE_KEY,
    storage: createSessionStorageAdapter(),
    persistSession: true,
    autoRefreshToken: true,
  }
});
